backend:
  name: git-gateway
  branch: test # Branch to update (optional; defaults to master)
media_library:
  name: uploadcare
  config:
    publicKey: 9b954d23a1102d31c3f8 # replace with your Public API key or use for testing env only
collections: 
  - label: "Homepage" # Used in routes, e.g., /admin/collections/blog
    name: "Homepage"
    files:
      - label: "Banner"
        name: "banner"
        format: "json"
        file: "/content/banner.json"
        fields:
          - label: "Test"
            name: "test"
            widget: "string"
      - label: "Projects"
        name: "projects"
        format: "json"
        file: "/content/projects.json"
        fields:
          - label: "Test"
            name: "test"
            widget: "string"
      - label: "Services"
        name: "services"
        format: "json"
        file: "/content/services.json"
        fields:
          - label: "Test"
            name: "test"
            widget: "string"
      - label: "Case Studies"
        name: "casestudies"
        format: "json"
        file: "/content/casestudies.json"
        fields:
          - label: "Test"
            name: "test"
            widget: "string"
      - label: "Team"
        name: "team"
        format: "json"
        file: "/content/team.json"
        fields: 
          - label: Team
            name: team
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Img1, name: img1, widget: image,default: "/logo.png"}
              - {label: Img2, name: img2, widget: string}
              - {label: Title, name: title, widget: string}
              
