backend:
  name: git-gateway
  branch: blog # Branch to update (optional; defaults to master)
media_folder: "/images/uploads" # Media files will be stored in the repo under images/uploads
collections:
  - name: 'blog' # Used in routes, e.g., /admin/collections/blog
    label: 'Blog Post' # Used in the UI
    folder: 'content/blog' # The path to the folder where the documents are stored
    media_folder: "/images/uploads" # override for blog collection
    public_folder: "/images/uploads" # override for blog collection
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md {{year}}-{{month}}-{{day}}-{{slug}}
    format: 'json'
    fields: # The fields for each document, usually in front matter
      - {label: "Lang", name: "lang", widget: "string"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "SEO Description", name: "description", widget: "text", required: true, pattern: ["^.{50,300}$", "Must be within 50 and 300 chars"]}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Thumbnail Image", name: "thumbnail", widget: "image", required: true}
      - {label: "Featured Blog Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      
  - label: "Homepage" # Used in routes, e.g., /admin/collections/blog
    name: "Homepage"
    files:
      - label: "Banner"
        name: "banner"
        format: "json"
        file: "/static/content/banner.json"
        fields:
          - label: "Title top line"
            name: "titleTop"
            widget: "string"
          - label: "Title bottom line"
            name: "titleBottom"
            widget: "string"
          - label: "Subheader"
            name: "subHeader"
            widget: "string"
          - label: "Button text"
            name: "buttonText"
            widget: "string"
      - label: "Flowchart"
        name: "flowchart"
        format: "json"
        file: "/static/content/flowchart.json"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Image on left"
            name: "leftImage"
            widget: "image"
          - label: "FLowchart steps"
            name: "steps"
            widget: "list"
            fields:
              - {label: "Number", name: "id", widget: "string"}
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "string"}
              - {label: "Image", name: "image", widget: "image"}
      - label: "Services"
        name: "services"
        format: "json"
        file: "/static/content/services.json"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Services"
            name: "services"
            widget: "list"
            fields:
              - {label: "Image title", name: "imageTitle", widget: "string"}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "string"}
      - label: "Promo Text"
        name: "promo"
        format: "json"
        file: "/static/content/promo.json"
        fields:
          - label: "Promo text"
            name: "promoText"
            widget: "string"
          - label: "Button text"
            name: "buttonText"
            widget: "string"
      - label: "Case Studies"
        name: "casestudies"
        format: "json"
        file: "/static/content/casestudies.json"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Case Studies"
            name: "caseStudies"
            widget: "list"
            fields:
              - {label: "Project title", name: "projectTitle", widget: "string"}
              - {label: "Subtitle", name: "subTitle", widget: "string"}
              - {label: "Type of project", name: "typeOfProject", widget: "string"}
              - {label: "Project image", name: "projectImage", widget: "image"}
              - {label: "Top image", name: "topImage", widget: "image"}
              - {label: "Logo", name: "logo", widget: "image"}
              - {label: "Intro", name: "ingro", widget: "string"}
              - {label: "Challenge 1", name: "challenge", widget: "string"}
              - {label: "Challenge 2", name: "challenge1", widget: "string"}
              - {label: "Centre image", name: "centreImage", widget: "image"}
              - {label: "Result 1", name: "result1", widget: "string"}
              - {label: "Result 2", name: "result2", widget: "string"}
              - {label: "Font", name: "font", widget: "image"}
              - {label: "Info 1", name: "info1", widget: "string"}
              - {label: "Info 2", name: "info2", widget: "string"}
              - {label: "Screenshot 1", name: "screenshot1", widget: "image"}
              - {label: Screenshot 2", name: "screenshot2", widget: "image"}
      - label: "Testimonials"
        name: "testimonials"
        format: "json"
        file: "/static/content/testimonials.json"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Testimonials"
            name: "testimonials"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Testimonial", name: "testimonial", widget: "string"}
              - {label: "Name", name: "name", widget: string}
              - {label: "Job title", name: "jobtitle", widget: "string"}
              - {label: "Company", name: "company", widget: "string"}
      - label: "Team"
        name: "team"
        format: "json"
        file: "/static/content/team.json"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Team"
            name: "team"
            widget: "list"
            fields:
              - {label: "First name", name: "firstname", widget: "string"}
              - {label: "Last name", name: "lastname", widget: "string"}
              - {label: "Image", name: "img1", widget: "image"}
              - {label: "Hover image", name: "img2", widget: "image"}
              - {label: "Title", name: "title", widget: "string"}
      - label: "About"
        name: "about"
        format: "json"
        file: "/static/content/about.json"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Desktop Section 1"
            name: "desktopSection1"
            widget: "string"
          - label: "Desktop Section 2"
            name: "desktopSection2"
            widget: "string"
          - label: "Desktop Section 3"
            name: "desktopSection3"
            widget: "string"
          - label: "Desktop Section 4"
            name: "desktopSection4"
            widget: "string"
          - label: "Mobile Section 1"
            name: "mobileSection1"
            widget: "string"
          - label: "Mobile Section 2"
            name: "mobileSection2"
            widget: "string"
          - label: "Mobile Section 3"
            name: "mobileSection3"
            widget: "string"
      - label: "Contact"
        name: "contact"
        format: "json"
        file: "/static/content/contact.json"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Telephone"
            name: "telephone"
            widget: "string"
          - label: "Address line 1"
            name: "addressLine1"
            widget: "string"
          - label: "Address line 2"
            name: "addressLine2"
            widget: "string"
          - label: "Name placeholder"
            name: "namePlaceholder"
            widget: "string"
          - label: "Email placeholder"
            name: "emailPlaceholder"
            widget: "string"
          - label: "Message placeholder"
            name: "messagePlaceholder"
            widget: "string"
          - label: "Button text"
            name: "buttonText"
            widget: "string"
      - label: "Footer"
        name: "footer"
        format: "json"
        file: "/static/content/footer.json"
        fields:
          - label: "Social Icons"
            name: "socialIcons"
            widget: "list"
            fields:
              - {label: Image, name: image, widget: image}
              - {label: Description, name: description, widget: string}
              - {label: Link, name: link, widget: string}
          - label: "Copyright"
            name: "copyright"
            widget: "string"
  - label: "Start a project form"
    name: "startaprojectform"
    files:
      - label: "Start a project form"
        name: "startaprojectform"
        format: "json"
        file: "/static/content/startaprojectform.json"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Instruction"
            name: "instruction"
            widget: "string"
          - label: "Contact title"
            name: "contactTitle"
            widget: "string"
          - label: "Company placeholder"
            name: "companyPlaceholder"
            widget: "string"
          - label: "Email placeholder"
            name: "emailPlaceholder"
            widget: "string"
          - label: "Name placeholder"
            name: "namePlaceholder"
            widget: "string"
          - label: "Telephone placeholder"
            name: "telPlaceholder"
            widget: "string"
          - label: "Website placeholder"
            name: "websitePlaceholder"
            widget: "string"
          - label: "Project scope title"
            name: "projectScopeTitle"
            widget: "string"
          - label: "Services to choose"
            name: "services"
            widget: "list"
            fields:
              - {label: "Icon", name: "icon", widget: "image"}
              - {label: "Yellow icon", name: "yellowIcon", widget: "image"}
              - {label: "Title", name: "title", widget: "string"}
          - label: "Timeframe title"
            name: "timeframeTitle"
            widget: "string"
          - label: "Timeframe"
            name: "timeframe"
            widget: "list"
          - label: "Goal title"
            name: "goalTitle"
            widget: "string"
          - label: "Goal placeholder"
            name: "goalPlaceholder"
            widget: "string"
          - label: "Brief upload button text"
            name: "goalUploadButtonText"
            widget: "string"
          - label: "Upload max size"
            name: "goalMaxLength"
            widget: "string"
          - label: "How did you hear about us title"
            name: "hearAboutUsTitle"
            widget: "string"
          - label: "How did you hear about us"
            name: "hearAboutUs"
            widget: "list"
          - label: "Button text"
            name: "buttonText"
            widget: "string"
          - label: "Tick icon"
            name: "tick"
            widget: "image"
  - label: "Thank you" # Used in routes, e.g., /admin/collections/blog
    name: "success"
    files:
      - label: "Thank you"
        name: "success"
        format: "json"
        file: "/static/content/success.json"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Message"
            name: "message"
            widget: "string"
          - label: "Button text"
            name: "buttonText"
            widget: "string"
  - label: "Meta data"
    name: "metadata"
    files: 
      - label: "Meta data"
        name: "metadata"
        format: "json"
        file: "/static/content/metadata.json"
        fields:
          - label: "Homepage meta title"
            name: "homepageTitle"
            widget: "string"
          - label: "Homepage meta description"
            name: "homepageDescription"
            widget: "string"
          - label: "Thank you meta title"
            name: "thankYouTitle"
            widget: "string"
          - label: "Thank you meta description"
            name: "thankYouDescription"
            widget: "string"
          - label: "Start a project form meta title"
            name: "startaprojectformTitle"
            widget: "string"
          - label: "Start a project form meta description"
            name: "startaprojectformDescription"
            widget: "string"
  - label: "Messages"
    name: "messages"
    files: 
      - label: "Messages"
        name: "messages"
        format: "json"
        file: "/static/content/messages.json"
        fields:
          - label: "Install web app on iOS"
            name: "installWebApp"
            widget: "string"
